RSS_FEEDS = [
    # --- German Agriculture ---
    {
        "name": "Proplanta Agrar-Nachrichten",
        "category": "agriculture",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.proplanta.de/agrar-nachrichten/rss-channel/",
        "website": "https://www.proplanta.de/agrar-nachrichten/",
    },
    {
        "name": "Proplanta Agrarpolitik",
        "category": "policy",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.proplanta.de/agrar-nachrichten/agrarpolitik/rss.xml",
        "website": "https://www.proplanta.de/agrar-nachrichten/agrarpolitik/",
    },
    # --- Landwirtschaftskammer Niedersachsen ---
    {
        "name": "LWK Niedersachsen - Neueste Meldungen",
        "category": "agriculture",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/rss_lwk_presse.rdf",
        "website": "https://www.lwk-niedersachsen.de/",
    },
    {
        "name": "LWK Niedersachsen - Agrarfoerderung",
        "category": "policy",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/services/rss/rss_lwk_agrarfoerderung.rdf",
        "website": "https://www.lwk-niedersachsen.de/agrarfoerderung/",
    },
    {
        "name": "LWK Niedersachsen - Pflanzenschutzdienst",
        "category": "crop_protection",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/services/rss/rss_lwk_pflanzenschutzdienst.rdf",
        "website": "https://www.lwk-niedersachsen.de/pflanzenschutz/",
    },
    {
        "name": "LWK Niedersachsen - Duengebehoerde",
        "category": "fertilizer",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/services/rss/rss_lwk_duengebehoerde.rdf",
        "website": "https://www.lwk-niedersachsen.de/duengebehoerde/",
    },
    {
        "name": "LWK Niedersachsen - Forstwirtschaft",
        "category": "forestry",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/rss_lwk_forstwirtschaft.rdf",
        "website": "https://www.lwk-niedersachsen.de/forstwirtschaft/",
    },
    {
        "name": "LWK Niedersachsen - Tierzucht",
        "category": "livestock",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lwk-niedersachsen.de/services/rss/rss_lwk_tierzucht.rdf",
        "website": "https://www.lwk-niedersachsen.de/tierzucht/",
    },
    # --- EU Agriculture ---
    {
        "name": "AgroGo EU Agriculture News",
        "category": "agriculture",
        "country": "EU",
        "language": "en",
        "rss_url": "https://agrogo.net/en/rss/news",
        "website": "https://agrogo.net/en/news",
    },
    {
        "name": "Eurostat - Agriculture, forestry and fisheries",
        "category": "statistics",
        "country": "EU",
        "language": "en",
        "rss_url": "https://ec.europa.eu/eurostat/rss.xml?theme=agr",
        "website": "https://ec.europa.eu/eurostat/web/agriculture/data",
    },
    {
        "name": "EFSA - News",
        "category": "food_safety",
        "country": "EU",
        "language": "en",
        "rss_url": "https://www.efsa.europa.eu/en/rss/news",
        "website": "https://www.efsa.europa.eu/en/news",
    },
    {
        "name": "EFSA - Publications",
        "category": "food_safety",
        "country": "EU",
        "language": "en",
        "rss_url": "https://www.efsa.europa.eu/en/rss/publications",
        "website": "https://www.efsa.europa.eu/en/publications",
    },
    {
        "name": "SmartAgriHubs (digital agriculture in EU)",
        "category": "digital_ag",
        "country": "EU",
        "language": "en",
        "rss_url": "https://smartagrihubs.eu/news/rss",
        "website": "https://smartagrihubs.eu/news",
    },
    # --- Precision Agriculture / AgTech ---
    {
        "name": "Global Ag Tech Initiative / PrecisionAg",
        "category": "precision_ag",
        "country": "global",
        "language": "en",
        "rss_url": "https://www.globalagtechinitiative.com/feed",
        "website": "https://www.globalagtechinitiative.com",
    },
    {
        "name": "Successful Farming - Technology",
        "category": "agritech",
        "country": "global",
        "language": "en",
        "rss_url": "https://www.agriculture.com/news/technology/rss",
        "website": "https://www.agriculture.com/news/technology",
    },
    # --- Drones Germany ---
    {
        "name": "Drones Magazin",
        "category": "drones",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.drones-magazin.de/feed",
        "website": "https://www.drones-magazin.de/",
    },
    {
        "name": "Droniq Blog",
        "category": "drones",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.droniq.de/de/blog?format=feed&type=rss",
        "website": "https://www.droniq.de/de/blog",
    },
    {
        "name": "Copting News",
        "category": "drones",
        "country": "DE",
        "language": "de",
        "rss_url": "https://copting.de/feed/",
        "website": "https://copting.de/en/news",
    },
    {
        "name": "Volocopter News",
        "category": "urban_air_mobility",
        "country": "DE",
        "language": "en",
        "rss_url": "https://www.volocopter.com/rss.xml",
        "website": "https://www.volocopter.com/newsroom/",
    },
    {
        "name": "Skycharge Blog",
        "category": "drones",
        "country": "DE",
        "language": "en",
        "rss_url": "https://skycharges.com/feed",
        "website": "https://skycharges.com/blog",
    },
    {
        "name": "Profly Center Blog",
        "category": "drones_training",
        "country": "DE",
        "language": "de",
        "rss_url": "https://proflycenter.de/feed/",
        "website": "https://proflycenter.de/blog/",
    },
    # --- Drone Regulation ---
    {
        "name": "Digital Platform for Unmanned Aviation (dipul.de)",
        "category": "uav_regulation",
        "country": "DE",
        "language": "de",
        "rss_url": "https://dipul.de/homepage/de/aktuell/feed/",
        "website": "https://dipul.de/homepage/de/aktuell/",
    },
    {
        "name": "Luftfahrt-Bundesamt - RSS Newsfeeds",
        "category": "aviation_regulation",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lba.de/SharedDocs/RSSFeeds/DE/_functions/rssfeed.xml?nn=632590",
        "website": "https://www.lba.de/DE/ServiceStartseite/Service/RSS.html",
    },
    {
        "name": "Luftfahrt-Bundesamt - Ereignismeldungen",
        "category": "aviation_incidents",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lba.de/SharedDocs/RSSFeeds/DE/U/U3_Ereignismeldungen.html",
        "website": "https://www.lba.de/DE/Luftfahrtunternehmen/Ereignismeldungen/ereignismeldungen_node.html",
    },
    {
        "name": "Luftfahrt-Bundesamt - Rundschreiben Flugbetrieb",
        "category": "aviation_ops",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lba.de/SharedDocs/RSSFeeds/DE/F/F2_Rundschreiben_Flugbetrieb.html",
        "website": "https://www.lba.de/DE/Luftfahrtunternehmen/Flugbetrieb/Rundschreiben/rundschreiben_node.html",
    },
    {
        "name": "Luftfahrt-Bundesamt - Luftfahrtpersonal",
        "category": "aviation_personnel",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lba.de/SharedDocs/RSSFeeds/DE/L/L3_2023-03_Aktualisierung_Berichte_Lehrberechtigte.html",
        "website": "https://www.lba.de/DE/Luftfahrtpersonal/luftfahrtpersonal_node.html",
    },
    {
        "name": "Luftfahrt-Bundesamt - Luftsicherheitsprogramme",
        "category": "aviation_security",
        "country": "DE",
        "language": "de",
        "rss_url": "https://www.lba.de/SharedDocs/RSSFeeds/DE/S/S5_Luftsicherheitsprogramme.html",
        "website": "https://www.lba.de/DE/Luftsicherheit/Luftsicherheitsprogramme/luftsicherheitsprogramme_node.html",
    },
    {
        "name": "EASA - Drones (UAS) News",
        "category": "uav_regulation",
        "country": "EU",
        "language": "en",
        "rss_url": "https://www.easa.europa.eu/en/newsroom-andevents/news/rss",
        "website": "https://www.easa.europa.eu/en/the-agency/faqs/drones-uas",
    },
]

# Categories relevant to AgroDrone Europe services
AGRODRONE_CATEGORIES = {
    "crop_protection": ["crop_protection", "agriculture", "fertilizer"],
    "seeding": ["agriculture", "digital_ag", "precision_ag"],
    "ndvi_monitoring": ["precision_ag", "digital_ag", "agritech", "statistics"],
    "drone_regulation": ["uav_regulation", "aviation_regulation", "aviation_ops", "aviation_security"],
    "drones_general": ["drones", "drones_training", "urban_air_mobility"],
    "policy": ["policy", "food_safety"],
}


def get_feeds_by_category(category: str | None = None) -> list[dict]:
    """Return feeds filtered by category. If None, return all feeds."""
    if category is None:
        return RSS_FEEDS
    target_cats = AGRODRONE_CATEGORIES.get(category, [category])
    return [f for f in RSS_FEEDS if f["category"] in target_cats]
