research_task:
  description: >
    Collect the latest news and information on {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list of dictionaries, each containing:
    - "title": The title of the news article.
    - "url": The URL where the article can be accessed.
    - "source": The name of the publication or source.
    
  agent: news_collector

fact_check_task:
  description: >
    Verify the accuracy of news articles collected on {topic}. 
    Use the Fact Checker tool for each article provided by the news collector.
    Only return the titles of articles that are determined to be factual.
  expected_output: >
    A list of strings, where each string is the title of an article that has been verified as factual.
    For example:
    [
      "AI Breakthrough in Medical Diagnosis",
      "New Study Shows Promise in Quantum Computing",
      "Tech Giants Collaborate on Ethical AI Guidelines"
    ]
  agent: fact_checker

summary_task:
  description: >
    Create concise summaries of news articles and reports on {topic}
  expected_output: >
    A dictionary containing:
    - "title": The title of the summary.
    - "summary": A brief overview of the main findings or conclusions.
    - "key_points": A list of key points or highlights from the summary.
    - "sources": A list of URLs where the information was sourced.
  agent: summary_writer

trend_task:
  description: >
    Analyze trends and patterns in news data related to {topic}
  expected_output: >
    A dictionary containing:
    - "main_trend": A brief description of the primary trend identified.
    - "sub_trends": A list of sub-trends related to the main trend.
    - "sentiment_analysis": A dictionary with:
      - "overall_sentiment": A numerical representation of the overall sentiment.
      - "sentiment_breakdown": A dictionary with percentages of positive, neutral, and negative sentiments.
    - "key_entities": A list of dictionaries, each with:
      - "name": The name of the entity.
      - "type": The type of entity (e.g., Technology, Person).
      - "frequency": The frequency of the entity's mention.
    - "timeline": A list of dictionaries, each with:
      - "date": The date of the event in ISO 8601 format.
      - "event": A brief description of the event.
  agent: trend_analyzer
